### ISSUE TITLE
hat Does Ethereum 3.0 Look Like?

### ISSUE THREAD

**Issue by riski2801** [ethereum/wiki#743]
Metis Runs Decentralized Economy

A Preliminary Research on Casper Network and Metis Protocol

Layer 1 blockchain is the foundation of all the DApps building on top of it, which is needless to emphasize the importance of its construction. Metis is building a decentralized platform on top of the Layer 1 network to enable projects and communities to easily create their decentralized company on the blockchain and manage all the community collaborations via blockchain-based tools. As with many other blockchain projects, Metis has built the MVP on Ethereum and is frustrated with the high gas cost, low efficiency in dealing with the on-chain transactions.

Although Metis is building the Optimistic Rollup based layer2 construct, we are still keen to find high performance, low-cost Layer 1 blockchains to build with. Ethereum 2.0 still has a long way to go. The commence of Beacon Chain and validators staking to run their nodes doesn't change the way Ethereum blockchain operates nowadays. 

So we did some preliminary research on Casper Network, and found some clues for Ethereum 3.0, which might come sooner than Ethereum 2.0.

Vision

Casper network aims to provide the scalability and features that enable blockchain to become part of more extensive application architecture and drive mass adoption from developers and enterprises.

Metis shares the same vision as the Casper network. The decentralized framework that Metis is building serves as an "enabler" for the general web2 developers, applications, and internet communities to port onto the blockchain quickly and worry-free.

The difference between Casper Network and Ethereum 2.0

Many people tend to compare the Casper network with Ethereum 2.0. However, Casper's real counterpart is Ethereum 3.0, which plans to include pure CBC-Casper and WebAssembly, two core features of the Casper network.

Ethereum 2.0 does not implement full CBC-Casper; it only includes Casper-FFG, which blends the liveness properties of Proof of Work (PoW) with the safety properties of CBC-Casper, and it might take 3-5 years to accomplish a full Ethereum 2.0(after phase 0,1, and 2).

With the most advanced concept and technology, and without the historical burden as Ethereum has, Casper network can jump out of the circle and build a new future-proof architecture, which is of high performance, security, and scalability.

Key features

As a builder, we care about the user experience when interacting with the Casper network besides the essential performance features.

For all the builders

No matter if you are an existing blockchain developer or a Web 2.0 developer with no blockchain experience, Casper network provides a user-friendly environment for you to learn, experience, and build. It's estimated that 26 million developers (including 7M open source developers) exist globally, while only 20 thousand developers among them are familiar with Solidity. Casper network provides an open coding standard to support Rust, Assembly, Script, and all the languages that could be compiled to WebAssembly (WASM). So Casper network is targeting a much larger audience.

Easy to migrate

Casper network provides a Solidity transpiler to support smart contracts transpiled from Solidity to Rust. And for the projects to experience Ethereum 3.0 early on, Casper network can provide the support to probe for issues after transpiling, fix parts of the code that did not transpile properly, test, and deploy the smart contract on the Casper network.

Correct-by-construction consensus ensures both safety and liveness at scale

Similar to the continuous innovation concept in the traditional CI/CD practice, building a protocol or a DApp also needs continuous construction, optimization, and upgrade, so the capability to be flexible in the development is super important. We found several features that are very fascinating.

A one-stop and build-in development and test environment. No need to look for other 3rd party services. The deployment is also very straightforward.

Well-developed API for auto-execution and checking the status(via GraphQL) of smart contracts, no need to make a webpage to see how it goes.

Real-time upgrade smart contracts on the chain, where on-chain contracts can be managed and governed like any other software. 

Assign different weights to “authorizing keys” of an account in the deployment to support the multi-signature function.

Flexible payment code to support various payment schemes that future businesses might want to adapt, and also enable DApp maintainers to pay for the transactions of their users to facilitate the onboarding of new users.

Governance mechanism

A key issue that most current protocols and DApps have is that the project is governed and controlled by giant whales or arbitrageurs, not the actual value creators in the community. Casper network provides a mechanism for on-chain governance with the weight of reputation power, which is accumulated by contribution in the community, not just sitting on the governance tokens one bought.

The synergy between Metis and Casper Network

Casper network is a robust and user-friendly infrastructure for DApps to build, run, and operate. From the technical perspective, Metis is a highly scalable and easy-to-use framework for DApps and community-based projects to launch their applications on the blockchain. Casper network can support Metis with the high scalability, high performance, low cost, and high-security features that it requires.

As an ecosystem partner, Metis is supplementing and enhancing the capabilities of  Casper network to engage with various Web2 and community-based uses cases that they plan to target, which may include Defi, Internet Communities, Open-Source Projects, Sharing Economy, Gig Economy, Crowdsourcing, and even Volunteers community. 

Building a decentralized application is a totally different story compared with the centralized one. The technical part is not that hard to learn and build thanks to the user-friendly environment that Casper Network provides. Since it is no longer the “I build, you use” model in the DApps, the real challenges and uncertainties are how to organize the decentralized power(chaos and no trust) from the community to be aligned with the project development. As the practice in the physical world, an entity (aka Company) is registered to conduct all the business activities. In the decentralized world, the counterpart of the company is the Decentralized Autonomous Company(DAC), and the DAC is not just created for governance, but also for managing all the collaborations that happened in the community.

With Metis, these projects can easily be ported onto the blockchain, create their DAC, buildup trust(via Optimistic Governance) among distrustful community members, use different tools(ComCo Framework) to manage the community activities, and community members can gain incentives and reputation power based on their contribution.

As a practical and handy framework contributed by Casper Network and Metis, builders can feel safe and easy to migrate or build their business on top of the architecture. Most importantly, Ethereum 3.0 + Layer 2 Management DAO opens the window for the real-world economy to run on top of the blockchain, which will bring mass adoption to the blockchain and also take blockchain to the main stage.

And this is what Ethereum 3.0 and the future of the Decentralized Economy looks like.

Contributed by Kevin and Yuan from Metis

**Comment by Mickey44-Mickey** [comment]
good
